
# This is a basic workflow to help you get started with Actions

name: jp-app-TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ TEST ]
  pull_request:
    branches: [ MAIN ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with: 
         node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
        
      - uses: burnett01/rsync-deployments@4.0
        name: next sync
        with:
          switches: -avzr --exclude=".git" --include="./node_nodules/" --include="./public/" --include="*.json"=""
          path: /
          remote_path: /root/home/TEST/nextjs-jpsblog
          remote_host: ${{ secrets.TEST_HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.PRIVATEKEY }}
                
          
      - uses: dawidd6/action-send-mail@v3
        name: Send mail
        with:
          server_address: ${{ secrets.EMAIL_SMTP }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Maniak Devops Challenge job result (TEST)
          to: jp.gomezfranco@gmail.com
          from: JP Gomez
      
      
